### ISSUE TITLE
Text to Speech is not working !

### ISSUE THREAD

**Issue by kiritoInd** [twilio-labs/call-gpt#16]
i have followed every instructions carefully but when i run ```npm run outbound``` it works fine  for speech to text but it does not respond with text to speech output on call 

![image](https://github.com/twilio-labs/call-gpt/assets/96108214/33b96dcd-66cd-45c8-ac9c-2c056464b5dd)

and i am using

![image](https://github.com/twilio-labs/call-gpt/assets/96108214/e6f45cf4-5de6-48c3-b1e0-a48604c9b8ea)

**Comment by cweems** [comment]
@kiritoInd Sorry to hear about the issue. I just tested with that voice ID (female British accent) and it appears to work for me.

Something similar happened to me at one point and I needed to upgrade to a paid Eleven Labs account. I believe their API enforces rate limiting if you request many recordings quickly. I expected to get a 429 error from them but I don't believe that was happening, which was confusing. It also reset for me and started working again for about a day.

The other possibility is that your app is having difficulty relaying websockets back to Twilio due to some kind of network configuration (e.g. firewall). If that is the case you might try deploying the app to a remote server without that restriction.

If you've modified any of the code please feel free to link to your changes so that I can take a look.

**Comment by kiritoInd** [comment]
it worked out ! (no changes)  Thankyou
