### ISSUE TITLE
Could you please provide the config for vercel deployment

### ISSUE THREAD

**Issue by gauravkesharwani** [twilio-labs/call-gpt#40]
I am trying to deploy to vercel, followed all the instructions available on the internet, but not able to do deploy on vercel, could you please provide config setting to deploy to vercel?

**Comment by cweems** [comment]
Hi @gauravkesharwani I spent a few hours looking into this. Unfortunately it seems like Vercel's serverless approach won't play well with the sustained websocket connection that this app requires: https://vercel.com/guides/do-vercel-serverless-functions-support-websocket-connections

You would need another back-end provider in addition to Vercel in order to handle the websockets, at which point you might as well just use something like Fly.io, EC2, etc. This would also overly complicate the setup of the app and add unnecessary overhead. Thanks for the suggestion but closing as won't-fix.

**Comment by gauravkesharwani** [comment]
I suspected the same, Thank you so much for taking the effort to confirm 🙏
